import rnftools

rnftools.lavender.Report(
	bam_dirs=["../../bams/ot-ikeda-best-match"],
	name="report_PE",
	keep_intermediate_files=True,
	allowed_delta=150,
)

rule all: input: rnftools.input()

include: rnftools.include()
